import pandas as pd

log_file_reading_interval = 1       # File reading interval (sec)

# +------------------------------------------------------------------+
# FILE TRANSMIT PATHS
# +------------------------------------------------------------------+

mt5_account_number = 475    # LAST 3 DIGITS OF MT5 ACCOUNT. MUST BE CHANGED BEFORE BUILDING EXE

# MT5 directory with OHLC log file (logging on active timeframe):

# ------------------------
# LIIKURI PATHS # HASH FOLDER MUST BE CHANGED BEFORE EXE BUILD
mt5_logging_file_path = (
    f'C:\\Users\\Liikurserv\\AppData\\Roaming\\MetaQuotes\\Terminal\\1D0E83E0BCAA42603583233CF21A762C\\MQL5\\Files\\'
    f'OHLCVData_{mt5_account_number}.csv'
)
# File with signal generated by Python script
buy_sell_signals_for_mt5_filepath_1 = (
     f'C:\\Users\\Liikurserv\\AppData\\Roaming\\MetaQuotes\\Terminal\\1D0E83E0BCAA42603583233CF21A762C\\MQL5\\Files\\'
     f'buy_sell_signals_from_python_1.txt'
     )

buy_sell_signals_for_mt5_filepath_2 = (
     f'C:\\Users\\Liikurserv\\AppData\\Roaming\\MetaQuotes\\Terminal\\1D0E83E0BCAA42603583233CF21A762C\\MQL5\\Files\\'
     f'buy_sell_signals_from_python_2.txt'
     )

# Levels PATH for NinjaTrader:
levels_path = (
    f'C:\\Users\\Liikurserv\\PycharmProjects\\RT_Ninja\\hardcoded_sr_levels.csv'
)

# SILLAMAE PATHS
# mt5_logging_file_path = (
#     f'C:\\Users\\Vova deduskin lap\\AppData\\Roaming\\MetaQuotes\\Terminal\\'
#     f'D0E8209F77C8CF37AD8BF550E51FF075\\MQL5\\Files\\OHLCVData_{mt5_account_number}.csv'
# )
#
# # File with signal generated by Python script
# buy_sell_signals_for_mt5_filepath = (
#      f'C:\\Users\\Vova deduskin lap\\AppData\\Roaming\\MetaQuotes\\Terminal\\'
#      f'D0E8209F77C8CF37AD8BF550E51FF075\\MQL5\\Files\\buy_sell_signals_from_python.txt'
#      )


def leave_only_last_line():
    with open(mt5_logging_file_path, 'r', encoding='utf-16') as file:
        lines = file.readlines()
        # Check if there's at least one line to keep
        if lines:
            with open(mt5_logging_file_path, 'w', encoding='utf-16')as file:
                file.write(lines[-1])  # Write only the first line back to the file


def get_dataframe_from_file():

    log_df = pd.read_csv(mt5_logging_file_path, sep=';', encoding='utf-16', engine='python')
    new_column_names = ['Ticker', 'Timeframe', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume']
    log_df.columns = new_column_names
    log_df['Datetime'] = pd.to_datetime(log_df['Date'] + ' ' + log_df['Time'], format='ISO8601')
    log_df.set_index('Datetime', inplace=True)
    dataframe_from_log = log_df.loc[:, ['Ticker', 'Date', 'Time', 'Open', 'High', 'Low', 'Close']]
    datetime_index = log_df.index
    first_date = str(datetime_index[0])

    return dataframe_from_log, first_date


def get_levels_from_file(first_date2):
    with open(levels_path, 'r', encoding='utf-8') as file:
        levels = [(first_date2, float(line.strip())) for line in file]
    return levels


def save_order_parameters_to_file(line_order_parameters):   # Called from orders_sender.py
    with open(buy_sell_signals_for_mt5_filepath_1, 'w', encoding='utf-8') as file:
        file.writelines(line_order_parameters)
        print('NEW ORDER IS SUCCESSFULLY SAVED TO FILE')

    with open(buy_sell_signals_for_mt5_filepath_2, 'w', encoding='utf-8') as file:
        file.writelines(line_order_parameters)
        print('NEW ORDER IS SUCCESSFULLY SAVED TO FILE')


